### ISSUE TITLE
Docs menu links results in 404

### ISSUE THREAD

**Issue by AlyssaAnna** [elsa-workflows/elsa-website#23]
When you are on:

https://elsa-workflows.github.io/elsa-core/

Go to the lower left corner menu under docs. None of the links are working and resulting in a 404

URLs behind the menu links:

**Getting started**: 
https://elsa-workflows.github.io/elsa-core/docs/installing-elsa-core

**Concepts:**
https://elsa-workflows.github.io/elsa-core/docs/concepts-workflows

**Guides:**
https://elsa-workflows.github.io/elsa-core/docs/concepts-workflows

The links seems to be missing /installation/ path after the /docs.

**Example of working link:** 
https://elsa-workflows.github.io/elsa-core/docs/installation/installing-elsa-core

**Comment by sfmskywalker** [comment]
Indeed. Thanks for reporting!

**Comment by sfmskywalker** [comment]
Fixed in bcc95c5799f2d20ad2ea6d42e516482772b9028c
