### ISSUE TITLE
how to use WorkflowExecutionContext 

### ISSUE THREAD

**Issue by PritiMaurya** [elsa-workflows/elsa-website#30]
also give proper syntax for OutPut

**Comment by sfmskywalker** [comment]
Hi @PritiMaurya, can you be a little bit more specific about what you mean with how to use `WorkflowExecutionContext`? Do you need some general information about it, or do you have a specific question?

Using activity output is documented [here](https://elsa-workflows.github.io/elsa-core/docs/next/expressions/expressions-javascript#activity-output-elsa-21).
