### ISSUE TITLE
Reference errors for 'GenerateSignalUrl' and 'WithBranches'.

### ISSUE THREAD

**Issue by VinsmokeJazz** [elsa-workflows/elsa-website#39]
I am getting the below reference errors in my dotnet core 3.1 application.
1.) I am trying to generate an absolute URL containing the security token as "context.GenerateSignalUrl("Approve")" but getting error as below:
'ActivityExecutionContext' does not contain a definition for 'GenerateSignalUrl' and no accessible extension method 'GenerateSignalUrl' accepting a first argument of type 'ActivityExecutionContext' could be found (are you missing a using directive or an assembly reference?)	

2.) I am trying to divide the workflow into multiple branches as "activity => activity.WithBranches("Approve", "Reject")" but getting erros as below:
'IActivityBuilder' does not contain a definition for 'WithBranches' and the best extension method overload 'ForkExtensions.WithBranches(ISetupActivity<Fork>, params string[])' requires a receiver of type 'ISetupActivity<Fork>'

It would be great if anyone could let me know what I am missing.

Thank you.

**Comment by joe704la** [comment]
@VinsmokeJazz How did you fix this?
